
name-template: "v$RESOLVED_VERSION-dev"
tag-template: "v$RESOLVED_VERSION-dev"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
prerelease: true
categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "patch"
      - "performance"
      - "refactor"
  default: patch

template: |
  # Music Assistant Queue Actions v$RESOLVED_VERSION

  $CHANGES
