get_queue_items:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: music_assistant
    limit:
      advanced: true
      example: 50
      default: 500
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    offset:
      advanced: true
      example: 50
      default: 0
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    entity:
      required: true
      domain: media_player
      integration: music_assistant
      supported_features:
        - media_player.MediaPlayerEntityFeature.PLAY_MEDIA