get_queue_items:
  fields:
    limit:
      advanced: true
      example: 50
      default: 500
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    offset:
      advanced: true
      example: 50
      default: 0
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
remove_queue_item:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
move_queue_item_up:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
move_queue_item_down:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
move_queue_item_next:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
play_queue_item:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA