get_queue_items:
  fields:
    limit:
      required: false
      example: 500
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    offset:
      required: false
      advanced: true
      example: 50
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    limit_before:
      required: false
      example: 5
      default: 5
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    limit_after:
      required: false
      example: 50
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
remove_queue_item:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
move_queue_item_up:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
move_queue_item_down:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
move_queue_item_next:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant
play_queue_item:
  fields:
    queue_item_id:
      required: true
      selector:
        text:
    entity:
      required: true
      selector:
        entity:
          domain: media_player
          integration: music_assistant